### ISSUE TITLE
Dozwolone pauzowanie gry w niedozwolonych momentach

### ISSUE THREAD

**Issue by sikorsoft** [NowinskiK/ProblemJasia#7]
Looknąłem, i tak:
- po zapauzowaniu - tylko jeden obrazek, ale po pauzie wystarczy zapauzować po ułożeniu, i kolejne - wracamy jednym elementem do rzutnika i zaraz mamy kolejnym
-  po Arnoldzie (on chyba ostatni jest) wyskakuje nam błąd
- sprawdzane na WIN7, poniżej raport
- See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProblemJasiaRetro.frmGame.mvARXN66a(Image  , Int32  , Boolean  )
   at ProblemJasiaRetro.frmGame.kWJGKUBjr(Boolean  )
   at ProblemJasiaRetro.frmGame.REgxXIoZV()
   at ProblemJasiaRetro.frmGame.eHtuSpphG(Int32  )
   at ProblemJasiaRetro.frmGame.fd9847S7Q()
   at ProblemJasiaRetro.frmGame.sRTiMfBgm()
   at ProblemJasiaRetro.frmGame.p9ebc42i6(Object  , KeyEventArgs  )
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3468.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ProblemJasiaRetro
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/Users/admin/Desktop/ProblemJasiaRetro_v2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3515.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
e1207413-970f-4233-b12f-92d5f2972b18
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/Users/admin/Desktop/ProblemJasiaRetro_v2.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3570.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by NowinskiK** [comment]
Dzięki za testy. Tak szybko udało Ci się przejść do Arnolda?
Nie rozumiem pierwszego punktu: "po zapauzowaniu".
Debugowałem na ostatniej planszy - nie mam żadnego błędu, gra kończy się poprawnie. Sprawdzę jeszcze potem plik wynikowy.

**Comment by sikorsoft** [comment]
Hejka!Jak naciśniesz pauzę podczas pierwszej gry, po ułożeniu sylwka u mnie się zawiesza. Dwa razy spacja i można "cofnąć: ostatni blok, po czym losujesz następny i... Za którymś razem tym jednym wylosowanym elementem układa się następna postać, po czym - po Arnoldzie się zawiesza, więc mniemam, że to ostatni obrazek (nie pamiętam już z Atari). Ponieważ wygenerował się raport - to go po prostu wkleiłem ;)Pozdrawiam,PawełOd: "Kamil Nowinski" ***@***.***&gt;Do: "NowinskiK/ProblemJasia" ***@***.***&gt;; Wysłane: 22:12 Piątek 2022-10-28Temat: Re: [NowinskiK/ProblemJasia] Błędy v. 1.02 (Issue #7)


Dzięki za testy. Tak szybko udało Ci się przejść do Arnolda?

Nie rozumiem pierwszego punktu: "po zapauzowaniu".

Debugowałem na ostatniej planszy - nie mam żadnego błędu, gra kończy się poprawnie. Sprawdzę jeszcze potem plik wynikowy.

**Comment by NowinskiK** [comment]
Występuje w wersji 1.0.2.
Problem z pauzowaniem i próbą wyciągnięcia elementu, gdy wszystkie są już ułożone powoduje wejście do nieskończonej pętli i zawieszenie gry.
